# Generated by Django 3.2.12 on 2022-02-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Batch",
        ),
    ]
